### ISSUE TITLE
wrong description?

### ISSUE THREAD

**Issue by johfel** [zatrazz/rldd#19]
Shouldn't it be
```
In opposite to the Linux ldd tool, it does not invoke the system loader but instead parses the loading information directly from either ELF or Mach-O files, ...
```
instead of
```
Similar to the Linux ldd tool, ...
```
?

See https://catonmat.net/ldd-arbitrary-code-execution how ldd works and how it uses the system loader.

**Comment by zatrazz** [comment]
Indeed it wording does make more sense, thanks. I fixed README with proposed wording.

And about lld, I know a bit how it works (I am a glibc maintainer, I hacked it sometime). And it is an interesting article, however it is not clear how you forced ldd on your experiments to issue a different loader than the defined one in ldd itself (and the list is define per-architecture at installation phase). Afaik issuing ldd, even with a binary with a different INTERP, won't actually run the ELF defined one (unless you actually change ldd itself).
